numero=input("Escribe un número del 1 al 10: ")
X=int(numero)
print(f"La tabla de multiplica es : ")
print(f"{X} * 1 ={1*X}  "" " )
print(f"{X} * 2 = {2*X} "" ")
print(f"{X} * 3 ={3*X } """)
print(f"{X} * 4 ={4*X } """)
print(f"{X} * 5 ={5*X } """)
print(f"{X} * 6 ={6*X } """)
print(f"{X} * 7 ={7*X } """)
print(f"{X} * 8 ={8*X } """)
print(f"{X} * 9 ={9*X } """)
print(f"{X} * 10 ={10*X } """)
